#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Deploys the UC3 (podcast-style dual-avatar) demo infrastructure.

.DESCRIPTION
    Provisions an isolated resource group (rg-uc3-podcast) in westeurope with:
      - Azure OpenAI (gpt-4.1 + text-embedding-3-small)
      - Azure AI Services (Speech / Batch Avatar Synthesis)
      - Cosmos DB (serverless, SQL API)
      - Storage Account (blob container 'podcasts', 30d lifecycle)
      - Container App + ACR + Log Analytics
      - System-assigned managed identity role assignments

    After deployment completes, outputs are written to demos/backend/.env.uc3
    and a reminder is printed for the Cosmos DB data-plane role (which cannot
    be assigned via ARM / Bicep).

.PARAMETER Location
    Azure region. Default: westeurope (required for DragonHD + Batch Avatar).

.PARAMETER DeploymentName
    ARM deployment name. Default: uc3-podcast-<timestamp>.

.PARAMETER SubscriptionId
    Optional. Switches to this subscription before deploying.

.EXAMPLE
    ./deploy.ps1
    ./deploy.ps1 -SubscriptionId 00000000-0000-0000-0000-000000000000
#>

[CmdletBinding()]
param(
    [string] $Location = 'westeurope',
    [string] $DeploymentName = "uc3-podcast-$(Get-Date -Format 'yyyyMMdd-HHmmss')",
    [string] $SubscriptionId
)

$ErrorActionPreference = 'Stop'
$InformationPreference = 'Continue'

$here        = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot    = Resolve-Path (Join-Path $here '..\..')
$templateFile = Join-Path $here 'main.bicep'
$paramsFile   = Join-Path $here 'main.parameters.json'
$envOut       = Join-Path $repoRoot 'demos\backend\.env.uc3'

Write-Host "== UC3 deployment ==" -ForegroundColor Cyan
Write-Host "Template : $templateFile"
Write-Host "Params   : $paramsFile"
Write-Host "Location : $Location"
Write-Host "Env file : $envOut"

# Check prerequisites
if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
    throw "Azure CLI 'az' not found. Install from https://aka.ms/installazurecli"
}

if ($SubscriptionId) {
    Write-Host "Setting subscription: $SubscriptionId"
    az account set --subscription $SubscriptionId | Out-Null
}

# Validate the template locally first
Write-Host "Building bicep..." -ForegroundColor Cyan
az bicep build --file $templateFile | Out-Null

Write-Host "Starting subscription deployment '$DeploymentName'..." -ForegroundColor Cyan
az deployment sub create `
    --name $DeploymentName `
    --location $Location `
    --template-file $templateFile `
    --parameters "@$paramsFile" `
    --output none

if ($LASTEXITCODE -ne 0) {
    throw "az deployment sub create failed with exit code $LASTEXITCODE"
}

Write-Host "Fetching deployment outputs..." -ForegroundColor Cyan
$outputsJson = az deployment sub show --name $DeploymentName --query properties.outputs -o json
if ($LASTEXITCODE -ne 0) {
    throw "Failed to read deployment outputs"
}
$outputs = $outputsJson | ConvertFrom-Json

# Write AZURE_* outputs to .env.uc3
$envDir = Split-Path -Parent $envOut
if (-not (Test-Path $envDir)) {
    New-Item -ItemType Directory -Force -Path $envDir | Out-Null
}

$lines = @(
    "# Generated by infra/uc3/deploy.ps1 on $(Get-Date -Format 'o')",
    "# Deployment: $DeploymentName"
)
foreach ($prop in $outputs.PSObject.Properties) {
    $key = $prop.Name
    if ($key -like 'AZURE_*') {
        $value = $prop.Value.value
        $lines += "$key=$value"
    }
}
Set-Content -Path $envOut -Value ($lines -join [Environment]::NewLine) -Encoding UTF8
Write-Host "Wrote $($lines.Count) lines to $envOut" -ForegroundColor Green

# Print the Cosmos RBAC hint (data-plane role cannot be assigned via ARM)
if ($outputs.PSObject.Properties.Name -contains 'COSMOS_RBAC_HINT') {
    Write-Host ""
    Write-Host "NEXT STEP — assign Cosmos data-plane role to the Container App identity:" -ForegroundColor Yellow
    Write-Host $outputs.COSMOS_RBAC_HINT.value -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Done." -ForegroundColor Green
